apiVersion: v1
kind: Pod
metadata:
  name: logging-wrong
spec:
  containers:
    - args:
        - /bin/sh
        - -c
        - mkdir /var/log; while true; do echo "Hi, I am logging to a file" >> /var/log/bad-idea.log; sleep 5; done
      image: busybox
      name: busybox
  restartPolicy: Never
