---
apiVersion: v1
kind: Service
metadata:
  name: example
  labels:
    name: example
spec:
  ports:
    - port: 12345
      targetPort: 12345
  clusterIP: None
  selector:
    app: example
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example
spec:
  selector:
    matchLabels:
      app: example
  serviceName: example
  replicas: 5
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - |
              echo "Replica $POD_INDEX listening";
              while true 
              do 
               echo $(nc -l -p 12345) 
              done;
          image: alpine
          name: listener
          ports:
            - containerPort: 12345
          env:
            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
      initContainers:
        - name: announcer
          image: alpine
          command:
            - /bin/sh
            - -c
            - |
              if [ "$POD_INDEX" -eq "0" ]; then
                echo "I am the first replica. No need to contact anyone."
              else
                i=0
                while [ $i -lt $POD_INDEX ]
                do
                  echo "Announcing myself to example-$i"
                  echo -n "Hello from example-$POD_INDEX" | nc "example-$i.example.example-statefulset.svc.cluster.local" 12345
                  true $(( i++ ))
                done
              fi
          env:
            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
