apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secret-example
  name: secret-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-example
  template:
    metadata:
      labels:
        app: secret-example
    spec:
      containers:
        - image: busybox
          name: busybox
          command:
            - /bin/sh
            - -c
            - sleep 3600;
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: example-secret
                  key: password
