apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ./resources/db-deployment.yml
  - ./resources/db-svc.yml

patchesStrategicMerge:
  - awesome-app-deploy-overlay.yml

namespace: awesome-app-dev

nameSuffix: "-dev"

commonLabels:
  env: dev

images:
  - name: bespinian/awesome-image
    newTag: 2.0.0

configMapGenerator:
  - name: awesome-app-config
    namespace: awesome-app
    behavior: merge
    literals:
      - dbHost=db-dev
      - appVersion=2.0.0
