# Default values for helm-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: bespinian/awesome-image
  pullPolicy: IfNotPresent
  tag: "1.0.0"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Overrides the generated service account name
  name: ""

service:
  type: ClusterIP
  port: 80

app:
  title: "Something awesome"
  version: "1.0.0"

db:
  host: "db.bespinian.io"
  local: false
