apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesome-app
  namespace: awesome-app
spec:
  template:
    spec:
      containers:
        - name: awesome-app
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
