apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-demo.fullname" . }}
  labels: 
    {{- include "helm-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector: 
    {{- include "helm-demo.selectorLabels" . | nindent 4 }}
